post http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMWJjNDI0OThkMzYyOTMzMjA2NDZjMiIsImlhdCI6MTY0NTk5NjgyOX0.zsOMmXoV84ks9PxnZW-_YdhIJpqATVkEN8jN4zEBJW0

{
    "content": "A chuparla",
    "important": true
}

###

get http://localhost:3001/api/notes

###

get http://localhost:3001/api/notes/62195fc88066f5ab1b79d3ff

###

put http://localhost:3001/api/notes/6219718244feb0973f1aed61
Content-Type: application/json

{
    "content": "Cambiando crud",
    "important": true
}

###

delete http://localhost:3001/api/notes/6219718244feb0973f1aed61

###
post http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Leo",
    "name": "Leo Pale",
    "password":"salainen"
}

###
get http://localhost:3001/api/users

###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Leo",
    "password": "salainen"
}