post http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMmI1YzJiMmViNGQ3MTVkNTViOTY3OCIsImlhdCI6MTY0NzEwMTk5Mn0.1jiYbVjIQN4quEnm0t0r5-VVenZmw3BUFIOBb4-5S5I

{
    "content": "No funciona",
    "important": true
}

###

get http://localhost:3001/api/notes

###

get http://localhost:3001/api/notes/622cd2a019617e8610f599f9

###

put http://localhost:3001/api/notes/622cd2a019617e8610f599f9
Content-Type: application/json

{
    "content": "Comprobando"
}



###

delete http://localhost:3001/api/image/6219718244feb0973f1aed61

###
post http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "Lol",
    "name": "Salainen",
    "password":"Prueba"
}

###
get http://localhost:3001/api/users

###
post http://localhost:3001/api/login
Content-Type: application/json

{
    "username": "Luichix",
    "password": "passRex"
}